# Generated by Django 5.1.5 on 2026-09-03 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled campaign', max_length=255)),
                ('list_name', models.CharField(blank=True, max_length=255)),
                ('step', models.PositiveSmallIntegerField(default=1)),
                ('use_case', models.CharField(default='Job application', max_length=64)),
                ('subject_template', models.CharField(blank=True, max_length=998)),
                ('body_template', models.TextField(blank=True)),
                ('tone', models.CharField(choices=[('Formal', 'Formal'), ('Warm', 'Warm'), ('Direct', 'Direct')], default='Formal', max_length=16)),
                ('intensity', models.CharField(choices=[('Tokens only', 'Tokens only'), ('Tokens + opener', 'Tokens + opener')], default='Tokens + opener', max_length=24)),
                ('grounding', models.TextField(blank=True, help_text='Source material the opener must quote')),
                ('state', models.CharField(choices=[('idle', 'Draft'), ('review', 'Reviewing'), ('done', 'Finished')], default='idle', max_length=16)),
                ('cursor', models.PositiveIntegerField(default=0, help_text='How many recipients have been reviewed')),
                ('approved', models.BooleanField(default=False, help_text='User ticked the send-it-myself checkbox')),
                ('working_hours_only', models.BooleanField(default=True)),
                ('batch_cap', models.PositiveIntegerField(default=20)),
                ('cooldown_hours', models.PositiveIntegerField(default=6)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_sent', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('attach_rule', models.CharField(blank=True, max_length=64)),
                ('file', models.FileField(blank=True, null=True, upload_to='campaign_docs/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('org', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('documents_attached', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('org', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('campaign', 'email')},
            },
        ),
    ]
