# Generated by Django 5.1.5 on 2026-09-03 11:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailThread',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('latest_timestamp', models.DateTimeField(db_index=True)),
                ('is_open', models.BooleanField(default=True)),
                ('brief_ask', models.CharField(blank=True, max_length=255)),
                ('brief_due_at', models.DateTimeField(blank=True, null=True)),
                ('brief_due_text', models.CharField(blank=True, max_length=120)),
                ('brief_why', models.CharField(blank=True, max_length=255)),
                ('brief_evidence', models.TextField(blank=True)),
                ('brief_confidence', models.CharField(blank=True, choices=[('high', 'High'), ('low', 'Low')], max_length=8)),
                ('brief_parsed_at', models.DateTimeField(blank=True, null=True)),
                ('brief_dismissed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-latest_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('from_email', models.EmailField(db_index=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('to', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=998)),
                ('preview', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('is_unread', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('has_attachment', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('priority', models.IntegerField(choices=[(0, 'Urgent'), (1, 'Soon'), (2, 'Later')], default=2)),
                ('needs_reply', models.BooleanField(default=False)),
                ('effort_minutes', models.PositiveIntegerField(default=4)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('topics', models.CharField(blank=True, help_text='Space-separated LLM topic keywords', max_length=255)),
                ('classified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inbox.mailthread')),
            ],
            options={
                'ordering': ['priority', '-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SlotAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('slot_key', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_assignments', to='inbox.mailmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(db_index=True, max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('list_unsubscribe', models.CharField(blank=True, help_text='Raw List-Unsubscribe header', max_length=1024)),
                ('opens_count', models.PositiveIntegerField(default=0)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('dismissals_count', models.PositiveIntegerField(default=0)),
                ('messages_per_month', models.PositiveIntegerField(default=0)),
                ('window_stats', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('muted', 'Blacklisted')], default='active', max_length=16)),
                ('muted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sender_name', 'sender_email'],
            },
        ),
        migrations.CreateModel(
            name='VipSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='CalendarSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_busy', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['user', 'date'], name='inbox_calen_user_id_6ceb6e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mailthread',
            index=models.Index(fields=['user', '-latest_timestamp'], name='inbox_mailt_user_id_29c30d_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['user', 'priority', '-timestamp'], name='inbox_mailm_user_id_24a167_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['user', 'needs_reply'], name='inbox_mailm_user_id_38603b_idx'),
        ),
        migrations.AddIndex(
            model_name='mailmessage',
            index=models.Index(fields=['user', 'from_email'], name='inbox_mailm_user_id_013d13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slotassignment',
            unique_together={('user', 'message', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'sender_email')},
        ),
        migrations.AlterUniqueTogether(
            name='vipsender',
            unique_together={('user', 'email')},
        ),
    ]
